
try(require("shiny")||install.packages("shiny"))
try(require("pastecs")||install.packages("pastecs"))
try(require("rpart")||install.packages("rpart"))
try(require("dplyr")||install.packages("dplyr"))
try(require("Hmisc")||install.packages("Hmisc"))
try(require("randomForest")||install.packages("randomForest"))
try(require("hydroGOF")||install.packages("hydroGOF"))

try(require("party")||install.packages("party"))
try(require("partykit")||install.packages("partykit"))

library(shiny)
library(pastecs)
library(dplyr)
library(rpart)
library(randomForest)
library(hydroGOF)
library(party)
library(partykit)